[package]
name = "fission"
version = "0.1.0"
authors = ["Shashank Singh <sshashank124@gmail.com>"]
edition = "2018"

[dependencies]
exr = "*"
graphite = { git = "https://github.com/sshashank124/graphite" }
num_cpus = "*"
objloader = { git = "https://github.com/sshashank124/objloader" }
rand_core = "*"
rand_pcg = "*"
scoped_threadpool = "*"
staticvec = "*"
yaml-rust = "*"

[profile.release]
opt-level = 3
panic = "abort"
lto = true
